upgrade node-sass to 0.7.0
after node-sass v0.7.0 hexo gets a wired `TypeError: undefined is not a function` when node-sass is called.  
I wasn't able to find the cause of the error.